dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: CgcGHf/lmuvGohq5hkl59QyPUh2Dz7kf1nh00/9waU9hJuH0dd3XO+hk5zeer6HPLPh8prRvr/DG2Rcp081m27AXmy2BE3yYkEyEESMFAbiiI1ZLttZstHOi1bO7rUSjJYh4+c97IlFmB/rlaSzjPH44naoZQbKo5cYhcRGM0jBDUg/BmPTRVhMQ3wUKldvzqs4YM8+NLGPHBc7KMQPXpoEjrde4orU0UEdS+ViP8+bahrwYXyk9PpuLusYG1PkXh5diKF29OiF829rH3GgzN4z5t3pEgGDLK0jmJ6qJAGwa3OPw98OcPzR8g78rwsDh8jLUJnIZzwJEIlXUup29lQyfv9PLYAEKV/MwBoRui5SUKDHR839ggWxnHzRN/Xpgq6iudUpmILLhz68fIRvLz4yL+5RSDRzg0kAvdL4fMaz7v0COeL+DhiGuw9rSYjpD2nvFa7tO3RR851hQLcGJO9/DNQlAm7wTgZGw7gMX13pUjK8WIpVsu2Dq3H6jsbLnMpGFMb1N8HF5bPPncKmDYsqYePlz/qA0jsiPRM08Hfuvbjy79PQ1MT+7K2jGDuisMpr0DJwPbPNGUzuw4edvhAwkM6mPvBoIh/hPI6/xSxq/HvCvGGCtRpF350/KbbSOfDyufV5cdTFrD8XA5m/o/MhUFbNhA7AQmiNyWEwrjoY=
  file: Gerbers/PIN-114_gerbers.zip
  on:
    repo: w4xzr/PIN-114
  skip_cleanup: 'true'
